# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_id', '0002_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id_desc',
            name='id',
        ),
        migrations.AlterField(
            model_name='id_desc',
            name='db_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
